[package]
name = "edutrack_desktop"
version = "1.0.0"
description = "EduTrack Africa desktop shell"
authors = ["Emmanuel Ouang-namou Adoum"]
edition = "2021"

[lib]
name = "edutrack_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
getrandom = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
