import { z } from 'zod';

export const PERSON_SEX_VALUES = ['M', 'F', 'AUTRE'] as const;
export type PersonSex = (typeof PERSON_SEX_VALUES)[number];

export const GUARDIAN_RELATIONSHIP_TYPES = ['PERE', 'MERE', 'TUTEUR', 'AUTRE'] as const;
export type GuardianRelationshipType = (typeof GUARDIAN_RELATIONSHIP_TYPES)[number];

/** List filters: show active records by default, archived records on demand. */
export const RECORD_STATUS_VALUES = ['active', 'archived'] as const;
export type RecordStatus = (typeof RECORD_STATUS_VALUES)[number];

// ---------------------------------------------------------------------------
// Shared field schemas
// ---------------------------------------------------------------------------

function emptyStringToNull(value: unknown) {
  if (typeof value === 'string' && value.trim().length === 0) {
    return null;
  }

  return value;
}

/** Optional fields from controlled forms, where blanks mean "not set". */
const peopleNullableTextSchema = z.preprocess(
  emptyStringToNull,
  z.string().trim().max(255).nullable().optional()
);
const peopleLongTextSchema = z.preprocess(
  emptyStringToNull,
  z.string().trim().max(500).nullable().optional()
);
const peopleOptionalUrlSchema = z.preprocess(
  emptyStringToNull,
  // eslint-disable-next-line @typescript-eslint/no-deprecated
  z.string().trim().url().max(500).nullable().optional()
);
const peopleOptionalEmailSchema = z.preprocess(
  emptyStringToNull,
  z.email().max(190).nullable().optional()
);

// ---------------------------------------------------------------------------
// Student
// ---------------------------------------------------------------------------

export const createStudentRequestSchema = z.object({
  // Default `{school.code}-{academicYearStart}-{NNI}` is generated by the
  // service when omitted; an explicit code (e.g. from the Excel import)
  // overrides it. Codes are durable identity and never reused.
  code: z.string().trim().min(1).max(64).optional(),
  firstName: z.string().trim().min(1).max(120),
  lastName: z.string().trim().min(1).max(120),
  sex: z.enum(PERSON_SEX_VALUES).nullable().optional(),
  dateOfBirth: z.iso.date().nullable().optional(),
  placeOfBirth: peopleNullableTextSchema,
  nationality: peopleNullableTextSchema,
  photoUrl: peopleOptionalUrlSchema,
  phone: peopleNullableTextSchema,
  email: peopleOptionalEmailSchema,
  address: peopleLongTextSchema,
});

// The code is durable identity and cannot be changed after creation.
export const updateStudentRequestSchema = createStudentRequestSchema.omit({ code: true }).partial();

export const studentResponseSchema = z.object({
  id: z.uuid(),
  schoolId: z.uuid(),
  code: z.string().min(1),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  sex: z.enum(PERSON_SEX_VALUES).nullable(),
  dateOfBirth: z.string().nullable(),
  placeOfBirth: z.string().nullable(),
  nationality: z.string().nullable(),
  photoUrl: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  isActive: z.boolean(),
  recordVersion: z.number().int().min(0),
  currentClassroom: z
    .object({
      id: z.string(),
      name: z.string(),
    })
    .nullable()
    .optional(),
});

export const studentListQuerySchema = z.object({
  search: z.string().trim().max(120).optional(),
  /** Filter by ACTIVE enrollment in the current year, at this class level. */
  classLevelId: z.uuid().optional(),
  /** Filter by ACTIVE enrollment in the current year, in this classroom. */
  classroomId: z.uuid().optional(),
  sex: z.enum(PERSON_SEX_VALUES).optional(),
  status: z.enum(RECORD_STATUS_VALUES).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export const paginatedStudentsResponseSchema = z.object({
  items: z.array(studentResponseSchema),
  total: z.number().int().min(0),
  limit: z.number().int().min(1),
  offset: z.number().int().min(0),
});

export const archiveStudentRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

// ---------------------------------------------------------------------------
// Guardian
// ---------------------------------------------------------------------------

export const createGuardianRequestSchema = z.object({
  firstName: z.string().trim().min(1).max(120),
  lastName: z.string().trim().min(1).max(120),
  phone: peopleNullableTextSchema,
  email: peopleOptionalEmailSchema,
  address: peopleLongTextSchema,
});

export const updateGuardianRequestSchema = createGuardianRequestSchema.partial();

export const guardianResponseSchema = z.object({
  id: z.uuid(),
  schoolId: z.uuid(),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  isActive: z.boolean(),
  recordVersion: z.number().int().min(0),
});

export const guardianListQuerySchema = z.object({
  search: z.string().trim().max(120).optional(),
  status: z.enum(RECORD_STATUS_VALUES).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export const paginatedGuardiansResponseSchema = z.object({
  items: z.array(guardianResponseSchema),
  total: z.number().int().min(0),
  limit: z.number().int().min(1),
  offset: z.number().int().min(0),
});

export const archiveGuardianRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

// ---------------------------------------------------------------------------
// Teacher
// ---------------------------------------------------------------------------

export const createTeacherRequestSchema = z.object({
  // Default `{school.code}-{academicYearStart}-{NNI}` is generated by the
  // service when omitted; an explicit code (e.g. from the Excel import)
  // overrides it. Codes are durable identity and never reused.
  code: z.string().trim().min(1).max(64).optional(),
  firstName: z.string().trim().min(1).max(120),
  lastName: z.string().trim().min(1).max(120),
  specialization: peopleNullableTextSchema,
  hireDate: z.iso.date().nullable().optional(),
  phone: peopleNullableTextSchema,
  email: peopleOptionalEmailSchema,
  address: peopleLongTextSchema,
});

// The code is durable identity and cannot be changed after creation. An
// optional recordVersion enables optimistic concurrency: when provided it must
// match the stored version or the update is rejected with a 409 conflict.
export const updateTeacherRequestSchema = createTeacherRequestSchema
  .omit({ code: true })
  .partial()
  .extend({ recordVersion: z.number().int().positive().optional() });

export const teacherResponseSchema = z.object({
  id: z.uuid(),
  schoolId: z.uuid(),
  code: z.string().min(1),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  specialization: z.string().nullable(),
  hireDate: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  // Optional login link: record status stays independent of the account status.
  userId: z.uuid().nullable(),
  isActive: z.boolean(),
  recordVersion: z.number().int().min(0),
  assignedClassrooms: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
      })
    )
    .optional(),
});

export const teacherListQuerySchema = z.object({
  search: z.string().trim().max(120).optional(),
  sex: z.enum(PERSON_SEX_VALUES).optional(),
  status: z.enum(RECORD_STATUS_VALUES).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export const paginatedTeachersResponseSchema = z.object({
  items: z.array(teacherResponseSchema),
  total: z.number().int().min(0),
  limit: z.number().int().min(1),
  offset: z.number().int().min(0),
});

export const archiveTeacherRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

/** Login account info shown on the teacher profile, independent of record status. */
export const teacherLoginViewSchema = z.object({
  userId: z.uuid(),
  username: z.string().min(1),
  isActive: z.boolean(),
});

export const teacherProfileResponseSchema = z.object({
  teacher: teacherResponseSchema,
  login: teacherLoginViewSchema.nullable(),
});

// No request body: a teacher login is created from the teacher record.
export const createTeacherLoginRequestSchema = z.object({});

/** Generated credentials are returned exactly once and never retrievable later. */
export const teacherLoginCreatedResponseSchema = z.object({
  userId: z.uuid(),
  username: z.string().min(1),
  initialPassword: z.string().min(1),
});

export const deactivateTeacherLoginRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

// ---------------------------------------------------------------------------
// Student-guardian links
// ---------------------------------------------------------------------------

export const linkStudentGuardianRequestSchema = z.object({
  guardianId: z.uuid(),
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES),
  isPrimary: z.boolean().optional(),
  isEmergency: z.boolean().optional(),
  notes: peopleLongTextSchema,
});

export const updateStudentGuardianLinkRequestSchema = z.object({
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES).optional(),
  isPrimary: z.boolean().optional(),
  isEmergency: z.boolean().optional(),
  notes: peopleLongTextSchema,
});

export const studentGuardianLinkResponseSchema = z.object({
  id: z.uuid(),
  studentId: z.uuid(),
  guardianId: z.uuid(),
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES),
  isPrimary: z.boolean(),
  isEmergency: z.boolean(),
  notes: z.string().nullable(),
  recordVersion: z.number().int().min(0),
});

export const studentGuardianLinkViewSchema = z.object({
  link: studentGuardianLinkResponseSchema,
  guardian: guardianResponseSchema,
});

export const studentProfileResponseSchema = z.object({
  student: studentResponseSchema,
  guardians: z.array(studentGuardianLinkViewSchema),
});

export const guardianStudentLinkViewSchema = z.object({
  link: studentGuardianLinkResponseSchema,
  student: studentResponseSchema,
});

export const guardianProfileResponseSchema = z.object({
  guardian: guardianResponseSchema,
  students: z.array(guardianStudentLinkViewSchema),
});

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type CreateStudentRequest = z.infer<typeof createStudentRequestSchema>;
export type UpdateStudentRequest = z.infer<typeof updateStudentRequestSchema>;
export type StudentResponse = z.infer<typeof studentResponseSchema>;
export type StudentListQuery = z.infer<typeof studentListQuerySchema>;
export type PaginatedStudentsResponse = z.infer<typeof paginatedStudentsResponseSchema>;
export type ArchiveStudentRequest = z.infer<typeof archiveStudentRequestSchema>;

export type CreateGuardianRequest = z.infer<typeof createGuardianRequestSchema>;
export type UpdateGuardianRequest = z.infer<typeof updateGuardianRequestSchema>;
export type GuardianResponse = z.infer<typeof guardianResponseSchema>;
export type GuardianListQuery = z.infer<typeof guardianListQuerySchema>;
export type PaginatedGuardiansResponse = z.infer<typeof paginatedGuardiansResponseSchema>;
export type ArchiveGuardianRequest = z.infer<typeof archiveGuardianRequestSchema>;

export type LinkStudentGuardianRequest = z.infer<typeof linkStudentGuardianRequestSchema>;
export type UpdateStudentGuardianLinkRequest = z.infer<
  typeof updateStudentGuardianLinkRequestSchema
>;
export type StudentGuardianLinkResponse = z.infer<typeof studentGuardianLinkResponseSchema>;
export type StudentProfileResponse = z.infer<typeof studentProfileResponseSchema>;
export type GuardianProfileResponse = z.infer<typeof guardianProfileResponseSchema>;

export type CreateTeacherRequest = z.infer<typeof createTeacherRequestSchema>;
export type UpdateTeacherRequest = z.infer<typeof updateTeacherRequestSchema>;
export type TeacherResponse = z.infer<typeof teacherResponseSchema>;
export type TeacherListQuery = z.infer<typeof teacherListQuerySchema>;
export type PaginatedTeachersResponse = z.infer<typeof paginatedTeachersResponseSchema>;
export type ArchiveTeacherRequest = z.infer<typeof archiveTeacherRequestSchema>;
export type TeacherLoginView = z.infer<typeof teacherLoginViewSchema>;
export type TeacherProfileResponse = z.infer<typeof teacherProfileResponseSchema>;
export type TeacherLoginCreatedResponse = z.infer<typeof teacherLoginCreatedResponseSchema>;
export type DeactivateTeacherLoginRequest = z.infer<typeof deactivateTeacherLoginRequestSchema>;
