import { z } from 'zod';

export const PERSON_SEX_VALUES = ['M', 'F', 'AUTRE'] as const;
export type PersonSex = (typeof PERSON_SEX_VALUES)[number];

export const GUARDIAN_RELATIONSHIP_TYPES = ['PERE', 'MERE', 'TUTEUR', 'AUTRE'] as const;
export type GuardianRelationshipType = (typeof GUARDIAN_RELATIONSHIP_TYPES)[number];

// ---------------------------------------------------------------------------
// Shared field schemas
// ---------------------------------------------------------------------------

function emptyStringToNull(value: unknown) {
  if (typeof value === 'string' && value.trim().length === 0) {
    return null;
  }

  return value;
}

/** Optional fields from controlled forms, where blanks mean "not set". */
const peopleNullableTextSchema = z.preprocess(
  emptyStringToNull,
  z.string().trim().max(255).nullable().optional()
);
const peopleLongTextSchema = z.preprocess(
  emptyStringToNull,
  z.string().trim().max(500).nullable().optional()
);
const peopleOptionalUrlSchema = z.preprocess(
  emptyStringToNull,
  // eslint-disable-next-line @typescript-eslint/no-deprecated
  z.string().trim().url().max(500).nullable().optional()
);
const peopleOptionalEmailSchema = z.preprocess(
  emptyStringToNull,
  z.email().max(190).nullable().optional()
);

// ---------------------------------------------------------------------------
// Student
// ---------------------------------------------------------------------------

export const createStudentRequestSchema = z.object({
  // Default `{school.code}-{academicYearStart}-{NNI}` is generated by the
  // service when omitted; an explicit code (e.g. from the Excel import)
  // overrides it. Codes are durable identity and never reused.
  code: z.string().trim().min(1).max(64).optional(),
  firstName: z.string().trim().min(1).max(120),
  lastName: z.string().trim().min(1).max(120),
  sex: z.enum(PERSON_SEX_VALUES).nullable().optional(),
  dateOfBirth: z.iso.date().nullable().optional(),
  placeOfBirth: peopleNullableTextSchema,
  nationality: peopleNullableTextSchema,
  photoUrl: peopleOptionalUrlSchema,
  phone: peopleNullableTextSchema,
  email: peopleOptionalEmailSchema,
  address: peopleLongTextSchema,
});

// The code is durable identity and cannot be changed after creation.
export const updateStudentRequestSchema = createStudentRequestSchema.omit({ code: true }).partial();

export const studentResponseSchema = z.object({
  id: z.uuid(),
  schoolId: z.uuid(),
  code: z.string().min(1),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  sex: z.enum(PERSON_SEX_VALUES).nullable(),
  dateOfBirth: z.string().nullable(),
  placeOfBirth: z.string().nullable(),
  nationality: z.string().nullable(),
  photoUrl: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  isActive: z.boolean(),
  recordVersion: z.number().int().min(0),
});

export const studentListQuerySchema = z.object({
  search: z.string().trim().max(120).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export const paginatedStudentsResponseSchema = z.object({
  items: z.array(studentResponseSchema),
  total: z.number().int().min(0),
  limit: z.number().int().min(1),
  offset: z.number().int().min(0),
});

export const archiveStudentRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

// ---------------------------------------------------------------------------
// Guardian
// ---------------------------------------------------------------------------

export const createGuardianRequestSchema = z.object({
  firstName: z.string().trim().min(1).max(120),
  lastName: z.string().trim().min(1).max(120),
  phone: peopleNullableTextSchema,
  email: peopleOptionalEmailSchema,
  address: peopleLongTextSchema,
});

export const updateGuardianRequestSchema = createGuardianRequestSchema.partial();

export const guardianResponseSchema = z.object({
  id: z.uuid(),
  schoolId: z.uuid(),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  isActive: z.boolean(),
  recordVersion: z.number().int().min(0),
});

export const guardianListQuerySchema = z.object({
  search: z.string().trim().max(120).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export const paginatedGuardiansResponseSchema = z.object({
  items: z.array(guardianResponseSchema),
  total: z.number().int().min(0),
  limit: z.number().int().min(1),
  offset: z.number().int().min(0),
});

export const archiveGuardianRequestSchema = z.object({
  reason: z.string().trim().min(3).max(500),
});

// ---------------------------------------------------------------------------
// Student-guardian links
// ---------------------------------------------------------------------------

export const linkStudentGuardianRequestSchema = z.object({
  guardianId: z.uuid(),
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES),
  isPrimary: z.boolean().optional(),
  isEmergency: z.boolean().optional(),
  notes: peopleLongTextSchema,
});

export const updateStudentGuardianLinkRequestSchema = z.object({
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES).optional(),
  isPrimary: z.boolean().optional(),
  isEmergency: z.boolean().optional(),
  notes: peopleLongTextSchema,
});

export const studentGuardianLinkResponseSchema = z.object({
  id: z.uuid(),
  studentId: z.uuid(),
  guardianId: z.uuid(),
  relationshipType: z.enum(GUARDIAN_RELATIONSHIP_TYPES),
  isPrimary: z.boolean(),
  isEmergency: z.boolean(),
  notes: z.string().nullable(),
  recordVersion: z.number().int().min(0),
});

export const studentGuardianLinkViewSchema = z.object({
  link: studentGuardianLinkResponseSchema,
  guardian: guardianResponseSchema,
});

export const studentProfileResponseSchema = z.object({
  student: studentResponseSchema,
  guardians: z.array(studentGuardianLinkViewSchema),
});

export const guardianStudentLinkViewSchema = z.object({
  link: studentGuardianLinkResponseSchema,
  student: studentResponseSchema,
});

export const guardianProfileResponseSchema = z.object({
  guardian: guardianResponseSchema,
  students: z.array(guardianStudentLinkViewSchema),
});

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type CreateStudentRequest = z.infer<typeof createStudentRequestSchema>;
export type UpdateStudentRequest = z.infer<typeof updateStudentRequestSchema>;
export type StudentResponse = z.infer<typeof studentResponseSchema>;
export type StudentListQuery = z.infer<typeof studentListQuerySchema>;
export type PaginatedStudentsResponse = z.infer<typeof paginatedStudentsResponseSchema>;
export type ArchiveStudentRequest = z.infer<typeof archiveStudentRequestSchema>;

export type CreateGuardianRequest = z.infer<typeof createGuardianRequestSchema>;
export type UpdateGuardianRequest = z.infer<typeof updateGuardianRequestSchema>;
export type GuardianResponse = z.infer<typeof guardianResponseSchema>;
export type GuardianListQuery = z.infer<typeof guardianListQuerySchema>;
export type PaginatedGuardiansResponse = z.infer<typeof paginatedGuardiansResponseSchema>;
export type ArchiveGuardianRequest = z.infer<typeof archiveGuardianRequestSchema>;

export type LinkStudentGuardianRequest = z.infer<typeof linkStudentGuardianRequestSchema>;
export type UpdateStudentGuardianLinkRequest = z.infer<
  typeof updateStudentGuardianLinkRequestSchema
>;
export type StudentGuardianLinkResponse = z.infer<typeof studentGuardianLinkResponseSchema>;
export type StudentProfileResponse = z.infer<typeof studentProfileResponseSchema>;
export type GuardianProfileResponse = z.infer<typeof guardianProfileResponseSchema>;
